/* DDL generated by allbow on  27SEP2021:17:50:54 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.ILLUSTRATION(
    IllustrationID num format=11. not null label='IllustrationID'
   ,Diagram char(1024) format=$1024.   label='Diagram'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
