/**
  @file
  @brief Datalines for LOCATION dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.Location ;
attrib 
LocationID                       length= 8      format=6. label="LocationID"
Name                             length= $100   format=$100. label="Name"
CostRate                         length= 8      format=12.4 label="CostRate"
Availability                     length= 8      format=10.2 label="Availability"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  LocationID
  Name                             :$char.
  CostRate
  Availability
  ModifiedDate
;
datalines4;
1,Tool Crib,0,0,1525132800
2,Sheet Metal Racks,0,0,1525132800
3,Paint Shop,0,0,1525132800
4,Paint Storage,0,0,1525132800
5,Metal Storage,0,0,1525132800
6,Miscellaneous Storage,0,0,1525132800
7,Finished Goods Storage,0,0,1525132800
10,Frame Forming,22.5,96,1525132800
20,Frame Welding,25,108,1525132800
30,Debur and Polish,14.5,120,1525132800
40,Paint,15.75,120,1525132800
45,Specialized Paint,18,80,1525132800
50,Subassembly,12.25,120,1525132800
60,Final Assembly,12.25,120,1525132800
;;;;
run;
proc append base=productn.Location data=work.Location;run;
