/* DDL generated by allbow on  27SEP2021:17:51:07 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTDOCUMENT(
    ProductID num format=11. not null label='ProductID'
   ,DocumentNode char(892) format=$HEX1784. not null label='DocumentNode'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
