/**
  @file
  @brief Datalines for PRODUCTCATEGORY dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ProductCategory ;
attrib 
ProductCategoryID                length= 8      format=11. label="ProductCategoryID"
Name                             length= $100   format=$100. label="Name"
rowguid                          length= $36    format=$36. label="rowguid"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ProductCategoryID
  Name                             :$char.
  rowguid                          :$char.
  ModifiedDate
;
datalines4;
1,Bikes,CFBDA25C-DF71-47A7-B81B-64EE161AA37C,1525132800
2,Components,C657828D-D808-4ABA-91A3-AF2CE02300E9,1525132800
3,Clothing,10A7C342-CA82-48D4-8A38-46A2EB089B74,1525132800
4,Accessories,2BE3BE36-D9A2-4EEE-B593-ED895D97C2A6,1525132800
;;;;
run;
proc append base=productn.ProductCategory data=work.ProductCategory;run;
