/* DDL generated by allbow on  27SEP2021:17:51:06 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTDESCRIPTION(
    ProductDescriptionID num format=11. not null label='ProductDescriptionID'
   ,Description char(800) format=$800. not null label='Description'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
