/* DDL generated by allbow on  27SEP2021:17:51:10 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTLISTPRICEHISTORY(
    ProductID num format=11. not null label='ProductID'
   ,StartDate num format=DATETIME22.3 not null label='StartDate'
   ,EndDate num format=DATETIME22.3   label='EndDate'
   ,ListPrice num format=21.4 not null label='ListPrice'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
