/**
  @file
  @brief Datalines for PRODUCTMODELILLUSTRATION dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ProductModelIllustration ;
attrib 
ProductModelID                   length= 8      format=11. label="ProductModelID"
IllustrationID                   length= 8      format=11. label="IllustrationID"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ProductModelID
  IllustrationID
  ModifiedDate
;
datalines4;
7,3,1704897662.167
10,3,1704897662.167
47,4,1704897662.183
47,5,1704897662.183
48,4,1704897662.183
48,5,1704897662.183
67,6,1704897662.2
;;;;
run;
proc append base=productn.ProductModelIllustration data=work.ProductModelIllustration;run;
