/* DDL generated by allbow on  27SEP2021:17:50:58 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTCATEGORY(
    ProductCategoryID num format=11. not null label='ProductCategoryID'
   ,Name char(100) format=$100. not null label='Name'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
