/* DDL generated by allbow on  27SEP2021:17:51:16 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTPRODUCTPHOTO(
    ProductID num format=11. not null label='ProductID'
   ,ProductPhotoID num format=11. not null label='ProductPhotoID'
   ,Primary num format=1. not null label='Primary'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
