/* DDL generated by allbow on  27SEP2021:17:51:04 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTCOSTHISTORY(
    ProductID num format=11. not null label='ProductID'
   ,StartDate num format=DATETIME22.3 not null label='StartDate'
   ,EndDate num format=DATETIME22.3   label='EndDate'
   ,StandardCost num format=21.4 not null label='StandardCost'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
