/* DDL generated by allbow on  27SEP2021:17:51:13 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.PRODUCTMODELILLUSTRATION(
    ProductModelID num format=11. not null label='ProductModelID'
   ,IllustrationID num format=11. not null label='IllustrationID'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
