/**
  @file
  @brief Datalines for SCRAPREASON dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ScrapReason ;
attrib 
ScrapReasonID                    length= 8      format=6. label="ScrapReasonID"
Name                             length= $100   format=$100. label="Name"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ScrapReasonID
  Name                             :$char.
  ModifiedDate
;
datalines4;
1,Brake assembly not as ordered,1525132800
2,Color incorrect,1525132800
3,Gouge in metal,1525132800
4,Drill pattern incorrect,1525132800
5,Drill size too large,1525132800
6,Drill size too small,1525132800
7,Handling damage,1525132800
8,Paint process failed,1525132800
9,Primer process failed,1525132800
10,Seat assembly not as ordered,1525132800
11,Stress test failed,1525132800
12,Thermoform temperature too high,1525132800
13,Thermoform temperature too low,1525132800
14,Trim length too long,1525132800
15,Trim length too short,1525132800
16,Wheel misaligned,1525132800
;;;;
run;
proc append base=productn.ScrapReason data=work.ScrapReason;run;
