/* DDL generated by allbow on  27SEP2021:17:51:32 */
/* SAS Flavour DDL for PRODUCTN. */
proc sql;
create table productn.UNITMEASURE(
    UnitMeasureCode char(6) format=$6. not null label='UnitMeasureCode'
   ,Name char(100) format=$100. not null label='Name'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
