/**
  @file
  @brief Datalines for UNITMEASURE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.UnitMeasure ;
attrib 
UnitMeasureCode                  length= $6     format=$6. label="UnitMeasureCode"
Name                             length= $100   format=$100. label="Name"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  UnitMeasureCode                  :$char.
  Name                             :$char.
  ModifiedDate
;
datalines4;
BOX,Boxes,1525132800
BTL,Bottle,1525132800
C,Celsius,1525132800
CAN,Canister,1525132800
CAR,Carton,1525132800
CBM,Cubic meters,1525132800
CCM,Cubic centimeter,1525132800
CDM,Cubic decimeter,1525132800
CM,Centimeter,1525132800
CM2,Square centimeter,1525132800
CR,Crate,1525132800
CS,Case,1525132800
CTN,Container,1525132800
DM,Decimeter,1525132800
DZ,Dozen,1525132800
EA,Each,1525132800
FT3,Cubic foot,1525132800
G,Gram,1525132800
GAL,Gallon,1525132800
IN,Inch,1525132800
KG,Kilogram,1525132800
KGV,Kilogram/cubic meter,1525132800
KM,Kilometer,1525132800
KT,Kiloton,1525132800
L,Liter,1525132800
LB,US pound,1525132800
M,Meter,1525132800
M2,Square meter,1525132800
M3,Cubic meter,1525132800
MG,Milligram,1525132800
ML,Milliliter,1525132800
MM,Millimeter,1525132800
OZ,Ounces,1525132800
PAK,Pack,1525132800
PAL,Pallet,1525132800
PC,Piece,1525132800
PCT,Percentage,1525132800
PT,"Pint, US liquid",1525132800
;;;;
run;
proc append base=productn.UnitMeasure data=work.UnitMeasure;run;
