/**
  @file
  @brief Datalines for ADDRESSTYPE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.AddressType ;
attrib 
AddressTypeID                    length= 8      format=11. label="AddressTypeID"
Name                             length= $100   format=$100. label="Name"
rowguid                          length= $36    format=$36. label="rowguid"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  AddressTypeID
  Name                             :$char.
  rowguid                          :$char.
  ModifiedDate
;
datalines4;
1,Billing,B84F78B1-4EFE-4A0E-8CB7-70E9F112F886,1525132800
2,Home,41BC2FF6-F0FC-475F-8EB9-CEC0805AA0F2,1525132800
3,Main Office,8EEEC28C-07A2-4FB9-AD0A-42D4A0BBC575,1525132800
4,Primary,24CB3088-4345-47C4-86C5-17B535133D1E,1525132800
5,Shipping,B29DA3F8-19A3-47DA-9DAA-15C84F4A83A5,1525132800
6,Archive,A67F238A-5BA2-444B-966C-0467ED9C427F,1525132800
;;;;
run;
proc append base=person.AddressType data=work.AddressType;run;
