/* DDL generated by allbow on  27SEP2021:17:50:21 */
/* SAS Flavour DDL for PERSON. */
proc sql;
create table person.BUSINESSENTITY(
    BusinessEntityID num format=11. not null label='BusinessEntityID'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
