/**
  @file
  @brief Datalines for CONTACTTYPE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ContactType ;
attrib 
ContactTypeID                    length= 8      format=11. label="ContactTypeID"
Name                             length= $100   format=$100. label="Name"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ContactTypeID
  Name                             :$char.
  ModifiedDate
;
datalines4;
1,Accounting Manager,1525132800
2,Assistant Sales Agent,1525132800
3,Assistant Sales Representative,1525132800
4,Coordinator Foreign Markets,1525132800
5,Export Administrator,1525132800
6,International Marketing Manager,1525132800
7,Marketing Assistant,1525132800
8,Marketing Manager,1525132800
9,Marketing Representative,1525132800
10,Order Administrator,1525132800
11,Owner,1525132800
12,Owner/Marketing Assistant,1525132800
13,Product Manager,1525132800
14,Purchasing Agent,1525132800
15,Purchasing Manager,1525132800
16,Regional Account Representative,1525132800
17,Sales Agent,1525132800
18,Sales Associate,1525132800
19,Sales Manager,1525132800
20,Sales Representative,1525132800
;;;;
run;
proc append base=person.ContactType data=work.ContactType;run;
