/* DDL generated by allbow on  27SEP2021:17:50:28 */
/* SAS Flavour DDL for PERSON. */
proc sql;
create table person.COUNTRYREGION(
    CountryRegionCode char(6) format=$6. not null label='CountryRegionCode'
   ,Name char(100) format=$100. not null label='Name'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
