/**
  @file
  @brief Datalines for COUNTRYREGION dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.CountryRegion ;
attrib 
CountryRegionCode                length= $6     format=$6. label="CountryRegionCode"
Name                             length= $100   format=$100. label="Name"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  CountryRegionCode                :$char.
  Name                             :$char.
  ModifiedDate
;
datalines4;
AD,Andorra,1525132800
AE,United Arab Emirates,1525132800
AF,Afghanistan,1525132800
AG,Antigua and Barbuda,1525132800
AI,Anguilla,1525132800
AL,Albania,1525132800
AM,Armenia,1525132800
AN,Netherlands Antilles,1525132800
AO,Angola,1525132800
AQ,Antarctica,1525132800
AR,Argentina,1525132800
AS,American Samoa,1525132800
AT,Austria,1525132800
AU,Australia,1525132800
AW,Aruba,1525132800
AZ,Azerbaijan,1525132800
BA,Bosnia and Herzegovina,1525132800
BB,Barbados,1525132800
BD,Bangladesh,1525132800
BE,Belgium,1525132800
BF,Burkina Faso,1525132800
BG,Bulgaria,1525132800
BH,Bahrain,1525132800
BI,Burundi,1525132800
BJ,Benin,1525132800
BM,Bermuda,1525132800
BN,Brunei,1525132800
BO,Bolivia,1525132800
BR,Brazil,1525132800
BS,"Bahamas, The",1525132800
BT,Bhutan,1525132800
BV,Bouvet Island,1525132800
BW,Botswana,1525132800
BY,Belarus,1525132800
BZ,Belize,1525132800
CA,Canada,1525132800
CC,Cocos (Keeling) Islands,1525132800
CD,Congo (DRC),1525132800
CF,Central African Republic,1525132800
CG,Congo,1525132800
CH,Switzerland,1525132800
CI,"Côte d'Ivoire",1525132800
CK,Cook Islands,1525132800
CL,Chile,1525132800
CM,Cameroon,1525132800
CN,China,1525132800
CO,Colombia,1525132800
CR,Costa Rica,1525132800
CS,Serbia and Montenegro,1525132800
CU,Cuba,1525132800
CV,Cape Verde,1525132800
CX,Christmas Island,1525132800
CY,Cyprus,1525132800
CZ,Czech Republic,1525132800
DE,Germany,1525132800
DJ,Djibouti,1525132800
DK,Denmark,1525132800
DM,Dominica,1525132800
DO,Dominican Republic,1525132800
DZ,Algeria,1525132800
EC,Ecuador,1525132800
EE,Estonia,1525132800
EG,Egypt,1525132800
ER,Eritrea,1525132800
ES,Spain,1525132800
ET,Ethiopia,1525132800
FI,Finland,1525132800
FJ,Fiji Islands,1525132800
FK,Falkland Islands (Islas Malvinas),1525132800
FM,Micronesia,1525132800
FO,Faroe Islands,1525132800
FR,France,1525132800
GA,Gabon,1525132800
GB,United Kingdom,1525132800
GD,Grenada,1525132800
GE,Georgia,1525132800
GF,French Guiana,1525132800
GH,Ghana,1525132800
GI,Gibraltar,1525132800
GL,Greenland,1525132800
GM,"Gambia, The",1525132800
GN,Guinea,1525132800
GP,Guadeloupe,1525132800
GQ,Equatorial Guinea,1525132800
GR,Greece,1525132800
GS,South Georgia and the South Sandwich Islands,1525132800
GT,Guatemala,1525132800
GU,Guam,1525132800
GW,Guinea-Bissau,1525132800
GY,Guyana,1525132800
HK,Hong Kong SAR,1525132800
HM,Heard Island and McDonald Islands,1525132800
HN,Honduras,1525132800
HR,Croatia,1525132800
HT,Haiti,1525132800
HU,Hungary,1525132800
ID,Indonesia,1525132800
IE,Ireland,1525132800
IL,Israel,1525132800
IN,India,1525132800
IO,British Indian Ocean Territory,1525132800
IQ,Iraq,1525132800
IR,Iran,1525132800
IS,Iceland,1525132800
IT,Italy,1525132800
JM,Jamaica,1525132800
JO,Jordan,1525132800
JP,Japan,1525132800
KE,Kenya,1525132800
KG,Kyrgyzstan,1525132800
KH,Cambodia,1525132800
KI,Kiribati,1525132800
KM,Comoros,1525132800
KN,Saint Kitts and Nevis,1525132800
KP,North Korea,1525132800
KR,Korea,1525132800
KW,Kuwait,1525132800
KY,Cayman Islands,1525132800
KZ,Kazakhstan,1525132800
LA,Laos,1525132800
LB,Lebanon,1525132800
LC,Saint Lucia,1525132800
LI,Liechtenstein,1525132800
LK,Sri Lanka,1525132800
LR,Liberia,1525132800
LS,Lesotho,1525132800
LT,Lithuania,1525132800
LU,Luxembourg,1525132800
LV,Latvia,1525132800
LY,Libya,1525132800
MA,Morocco,1525132800
MC,Monaco,1525132800
MD,Moldova,1525132800
MG,Madagascar,1525132800
MH,Marshall Islands,1525132800
MK,"Macedonia, Former Yugoslav Republic of",1525132800
ML,Mali,1525132800
MM,Myanmar,1525132800
MN,Mongolia,1525132800
MO,Macao SAR,1525132800
MP,Northern Mariana Islands,1525132800
MQ,Martinique,1525132800
MR,Mauritania,1525132800
MS,Montserrat,1525132800
MT,Malta,1525132800
MU,Mauritius,1525132800
MV,Maldives,1525132800
MW,Malawi,1525132800
MX,Mexico,1525132800
MY,Malaysia,1525132800
MZ,Mozambique,1525132800
NA,Namibia,1525132800
NC,New Caledonia,1525132800
NE,Niger,1525132800
NF,Norfolk Island,1525132800
NG,Nigeria,1525132800
NI,Nicaragua,1525132800
NL,Netherlands,1525132800
NO,Norway,1525132800
NP,Nepal,1525132800
NR,Nauru,1525132800
NU,Niue,1525132800
NZ,New Zealand,1525132800
OM,Oman,1525132800
PA,Panama,1525132800
PE,Peru,1525132800
PF,French Polynesia,1525132800
PG,Papua New Guinea,1525132800
PH,Philippines,1525132800
PK,Pakistan,1525132800
PL,Poland,1525132800
PM,Saint Pierre and Miquelon,1525132800
PN,Pitcairn Islands,1525132800
PR,Puerto Rico,1525132800
PS,Palestinian Authority,1525132800
PT,Portugal,1525132800
PW,Palau,1525132800
PY,Paraguay,1525132800
QA,Qatar,1525132800
RE,Réunion,1525132800
RO,Romania,1525132800
RU,Russia,1525132800
RW,Rwanda,1525132800
SA,Saudi Arabia,1525132800
SB,Solomon Islands,1525132800
SC,Seychelles,1525132800
SD,Sudan,1525132800
SE,Sweden,1525132800
SG,Singapore,1525132800
SH,Saint Helena,1525132800
SI,Slovenia,1525132800
SJ,Svalbard and Jan Mayen,1525132800
SK,Slovakia,1525132800
SL,Sierra Leone,1525132800
SM,San Marino,1525132800
SN,Senegal,1525132800
SO,Somalia,1525132800
SR,Suriname,1525132800
ST,São Tomé and Príncipe,1525132800
SV,El Salvador,1525132800
SY,Syria,1525132800
SZ,Swaziland,1525132800
TC,Turks and Caicos Islands,1525132800
TD,Chad,1525132800
TF,French Southern and Antarctic Lands,1525132800
TG,Togo,1525132800
TH,Thailand,1525132800
TJ,Tajikistan,1525132800
TK,Tokelau,1525132800
TL,Timor-Leste,1525132800
TM,Turkmenistan,1525132800
TN,Tunisia,1525132800
TO,Tonga,1525132800
TR,Turkey,1525132800
TT,Trinidad and Tobago,1525132800
TV,Tuvalu,1525132800
TW,Taiwan,1525132800
TZ,Tanzania,1525132800
UA,Ukraine,1525132800
UG,Uganda,1525132800
UM,U.S. Minor Outlying Islands,1525132800
US,United States,1525132800
UY,Uruguay,1525132800
UZ,Uzbekistan,1525132800
VA,Vatican City,1525132800
VC,Saint Vincent and the Grenadine,1525132800
VE,Venezuela,1525132800
VG,"Virgin Islands, British",1525132800
VI,"Virgin Islands, U.S.",1525132800
VN,Vietnam,1525132800
VU,Vanuatu,1525132800
WF,Wallis and Futuna,1525132800
WS,Samoa,1525132800
YE,Yemen,1525132800
YT,Mayotte,1525132800
ZA,South Africa,1525132800
ZM,Zambia,1525132800
ZW,Zimbabwe,1525132800
;;;;
run;
proc append base=person.CountryRegion data=work.CountryRegion;run;
