/* DDL generated by allbow on  27SEP2021:17:50:32 */
/* SAS Flavour DDL for PERSON. */
proc sql;
create table person.PASSWORD(
    BusinessEntityID num format=11. not null label='BusinessEntityID'
   ,PasswordHash char(128) format=$128. not null label='PasswordHash'
   ,PasswordSalt char(10) format=$10. not null label='PasswordSalt'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
