/* DDL generated by allbow on  27SEP2021:17:50:37 */
/* SAS Flavour DDL for PERSON. */
proc sql;
create table person.PERSONPHONE(
    BusinessEntityID num format=11. not null label='BusinessEntityID'
   ,PhoneNumber char(50) format=$50. not null label='PhoneNumber'
   ,PhoneNumberTypeID num format=11. not null label='PhoneNumberTypeID'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
