/**
  @file
  @brief Datalines for PHONENUMBERTYPE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.PhoneNumberType ;
attrib 
PhoneNumberTypeID                length= 8      format=11. label="PhoneNumberTypeID"
Name                             length= $100   format=$100. label="Name"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  PhoneNumberTypeID
  Name                             :$char.
  ModifiedDate
;
datalines4;
1,Cell,1828790362.273
2,Home,1828790362.273
3,Work,1828790362.273
;;;;
run;
proc append base=person.PhoneNumberType data=work.PhoneNumberType;run;
