/* DDL generated by allbow on  27SEP2021:17:50:40 */
/* SAS Flavour DDL for PERSON. */
proc sql;
create table person.PHONENUMBERTYPE(
    PhoneNumberTypeID num format=11. not null label='PhoneNumberTypeID'
   ,Name char(100) format=$100. not null label='Name'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
