/**
  @file
  @brief Datalines for SHIPMETHOD dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ShipMethod ;
attrib 
ShipMethodID                     length= 8      format=11. label="ShipMethodID"
Name                             length= $100   format=$100. label="Name"
ShipBase                         length= 8      format=21.4 label="ShipBase"
ShipRate                         length= 8      format=21.4 label="ShipRate"
rowguid                          length= $36    format=$36. label="rowguid"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ShipMethodID
  Name                             :$char.
  ShipBase
  ShipRate
  rowguid                          :$char.
  ModifiedDate
;
datalines4;
1,XRQ - TRUCK GROUND,3.95,0.99,6BE756D9-D7BE-4463-8F2C-AE60C710D606,1525132800
2,ZY - EXPRESS,9.95,1.99,3455079B-F773-4DC6-8F1E-2A58649C4AB8,1525132800
3,OVERSEAS - DELUXE,29.95,2.99,22F4E461-28CF-4ACE-A980-F686CF112EC8,1525132800
4,OVERNIGHT J-FAST,21.95,1.29,107E8356-E7A8-463D-B60C-079FFF467F3F,1525132800
5,CARGO TRANSPORT 5,8.99,1.49,B166019A-B134-4E76-B957-2B0490C610ED,1525132800
;;;;
run;
proc append base=purchsng.ShipMethod data=work.ShipMethod;run;
