/* DDL generated by allbow on  27SEP2021:17:51:49 */
/* SAS Flavour DDL for PURCHSNG. */
proc sql;
create table purchsng.SHIPMETHOD(
    ShipMethodID num format=11. not null label='ShipMethodID'
   ,Name char(100) format=$100. not null label='Name'
   ,ShipBase num format=21.4 not null label='ShipBase'
   ,ShipRate num format=21.4 not null label='ShipRate'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
