/* DDL generated by allbow on  27SEP2021:17:50:04 */
/* SAS Flavour DDL for HR. */
proc sql;
create table hr.DEPARTMENT(
    DepartmentID num format=6. not null label='DepartmentID'
   ,Name char(100) format=$100. not null label='Name'
   ,GroupName char(100) format=$100. not null label='GroupName'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
