/**
  @file
  @brief Datalines for DEPARTMENT dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.Department ;
attrib 
DepartmentID                     length= 8      format=6. label="DepartmentID"
Name                             length= $100   format=$100. label="Name"
GroupName                        length= $100   format=$100. label="GroupName"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  DepartmentID
  Name                             :$char.
  GroupName                        :$char.
  ModifiedDate
;
datalines4;
1,Engineering,Research and Development,1525132800
2,Tool Design,Research and Development,1525132800
3,Sales,Sales and Marketing,1525132800
4,Marketing,Sales and Marketing,1525132800
5,Purchasing,Inventory Management,1525132800
6,Research and Development,Research and Development,1525132800
7,Production,Manufacturing,1525132800
8,Production Control,Manufacturing,1525132800
9,Human Resources,Executive General and Administration,1525132800
10,Finance,Executive General and Administration,1525132800
11,Information Services,Executive General and Administration,1525132800
12,Document Control,Quality Assurance,1525132800
13,Quality Assurance,Quality Assurance,1525132800
14,Facilities and Maintenance,Executive General and Administration,1525132800
15,Shipping and Receiving,Inventory Management,1525132800
16,Executive,Executive General and Administration,1525132800
;;;;
run;
proc append base=hr.Department data=work.Department;run;
