/* DDL generated by allbow on  27SEP2021:17:50:09 */
/* SAS Flavour DDL for HR. */
proc sql;
create table hr.EMPLOYEEPAYHISTORY(
    BusinessEntityID num format=11. not null label='BusinessEntityID'
   ,RateChangeDate num format=DATETIME22.3 not null label='RateChangeDate'
   ,Rate num format=21.4 not null label='Rate'
   ,PayFrequency num format=4. not null label='PayFrequency'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
