/**
  @file
  @brief Datalines for JOBCANDIDATE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.JobCandidate ;
attrib 
JobCandidateID                   length= 8      format=11. label="JobCandidateID"
BusinessEntityID                 length= 8      format=11. label="BusinessEntityID"
Resume                           length= $1024  format=$1024. label="Resume"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  JobCandidateID
  BusinessEntityID
  Resume                           :$char.
  ModifiedDate
;
datalines4;
1,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix/><ns:Name.First>Shai</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Bassli</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>
I am an experienced and versatile machinist who can operate a range of machinery personally as well as supervise the work of other machinists. I specialize in diagnostics and precision inspection, have expertise in reading blueprints, and am able to call on strong interpersonal and communication skills to guide the work of other production machinists whose work I am called upon to inspect. 
My degree in mechanical engineering affords me a better theoretical understanding and mathematical background than many other candidates in the machinist trade.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>2000-06-01Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-09-30Z</ns:Emp.EndDate><ns:Emp.OrgName>Wingtip Toys</ns:Emp.OrgName><ns:Emp.JobTitle>Lead Machinist</ns:Emp.JobTitle><ns:Emp.',1498176000
2,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix>Mr.</ns:Name.Prefix><ns:Name.First>Max</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Benson</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>3 years recent experience as a go-cart production line manager. Responsibilities included planning the production line budget, ordering parts, and overseeing all quality assurance procedures.
Prior to production management, worked 5 years on go-cart production lines (3 years while in college and for 2 years after), with increasing responsibilities over time. Responsibilities started with basic assembly and grew to quality assurance lead for brake systems.
Led an ISO 9000 certification process. Passed state exams for chemical and industrial safety. Recently recertified in basic first aid.
Avid cycler, placing in the top five in two Orlando-area races.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>1994-06-15Z</ns:Emp.StartDate><ns:Emp.OrgName>Wingtip T',1498176000
3,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix>Mr.</ns:Name.Prefix><ns:Name.First>Krishna</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Sunkammurali</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills> Expert in C# and Visual Basic 6.0. 7 years experience in object-oriented programming. Familiar with ASP.Net and the .NET Framework. Design experience with both Windows and Web user interfaces.
5 years experience in programming against MS SQL Server 7.0 and 2000. Familiar with ODBC, OLE DB, ADO, and ADO.NET. Conversant with T-SQL, skilled at writing stored procedures.
Excellent organizational, interpersonal, written and verbal communication skills.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>1998-08-31Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-12-28Z</ns:Emp.EndDate><ns:Emp.OrgName>Trey Research</ns:Emp.OrgName><ns:Emp.JobTitle>Senior Developer</ns:Emp.JobTitle><ns:Emp.Responsibility> Used C# and ASP.NET to create several intranet applicati',1498176000
4,274,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix>Mr.</ns:Name.Prefix><ns:Name.First>Stephen</ns:Name.First><ns:Name.Middle>Y </ns:Name.Middle><ns:Name.Last>Jiang</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills> Considerable expertise in all areas of the sales cycle. 13 years of achievement in increasing organization revenue. Experience in sales planning and forecasting, customer development, and multiple selling techniques. 5 years of experience in sales management, including lead generation, sales force leadership, and territory management. Leverage management style and technical ability to effectively manage and communicate with a distributed sales force composed of field representatives, product demonstrators, and vendors.
Excellent communication and presentation skills.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>1998-03-01Z</ns:Emp.StartDate><ns:Emp.EndDate>2000-12-30Z</ns:Emp.EndDate><ns:Emp.OrgName>Wide World Imports</ns:Emp.O',1703356341.313
5,.,"<ns:Resume xmlns:ns=""http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume""><ns:Name><ns:Name.Prefix>M.</ns:Name.Prefix><ns:Name.First>Thierry</ns:Name.First><ns:Name.Middle/><ns:Name.Last>D'Hers</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>Connaissances approfondies de tous les secteurs du cycle des ventes. 13 années d'expérience consacrées à l'augmentation du chiffre d'affaires de différentes entreprises. Expérience en planification et en prévision des ventes, en développement de la clientèle et en diverses techniques de vente. 5 années d'expérience en gestion des ventes, notamment en génération de prospects, direction de l'équipe de vente et gestion de zones géographiques. Style de gestion avec effet de levier et aptitude technique à gérer et à communiquer efficacement avec une équipe de vente répartie dans plusieurs agences et composée de représentants commerciaux, de démonstrateurs de produits et de vendeurs.
Excellentes compétences en matière de communicat",1498176000
6,.,"<ns:Resume xmlns:ns=""http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume""><ns:Name><ns:Name.Prefix>M.</ns:Name.Prefix><ns:Name.First>Christian</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Kleinerman</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>3 années d'expérience récente en tant que responsable d'une ligne de production de karts. Mes responsabilités comprenaient la planification du budget de la ligne de production, la commande des pièces et la supervision de toutes les procédures d'assurance qualité.
Avant la gestion de la production, j'ai travaillé pendant 5 ans sur des lignes de production de karts (3 ans pendant mes études et 2 ans ensuite). Mes responsabilités se sont élargies progressivement. J'ai commencé par le simple montage de pièces avant d'accéder au poste de responsable de la qualité des systèmes de freinage.
Mise en place d'un processus de certification ISO 9000. Diplômes d'état dans le domaine de la sécurité chimique et industrielle. Diplôme réce",1498176000
7,.,"<ns:Resume xmlns:ns=""http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume""><ns:Name><ns:Name.Prefix>M.</ns:Name.Prefix><ns:Name.First>Lionel</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Penuchot</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>Mécanicien expérimenté et polyvalent qui peut utiliser diverses machines ou superviser le travail d'autres mécaniciens. Je suis spécialisé dans les diagnostics et l'inspection de précision. Je sais lire des plans et peux faire appel à mes compétences en matière de communication pour guider le travail d'autres mécaniciens de production dont je suis amené à inspecter le travail. 
Mon diplôme en ingénierie mécanique me confère des connaissances théoriques et mathématiques particulièrement utiles dans mon travail.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>2000-06-15Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-09-11Z</ns:Emp.EndDate><ns:Emp.OrgName>Jouets en folie</ns:Emp.OrgName><ns:Emp.JobTitle>Chef mécanicien</ns:Emp.JobTitle><",1498176000
8,212,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix/><ns:Name.First>Peng</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Wu</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>熟悉所有销售环节，专业知识丰富。13 年来，为提高公司收入成绩卓著。在计划和预测销售、发展客户以及运用多种销售技巧方面具有一定经验。
具有五年的销售管理经验，包括客户线索生成、销售人员管理以及销售区域管理。在管理由现场销售代表、产品演示人员和供应商组成的分布式销售网络过程中，能够利用各种管理风格和专业技能来进行有效管理和沟通。
极佳的沟通和表达能力
    </ns:Skills><ns:Employment><ns:Emp.StartDate>1998-03-31Z</ns:Emp.StartDate><ns:Emp.OrgName>Wide World Imports</ns:Emp.OrgName><ns:Emp.JobTitle>销售经理</ns:Emp.JobTitle><ns:Emp.Responsibility>负责管理由 20 名销售代表和 5 名支持人员组成的跨 5',1703356341.267
9,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix/><ns:Name.First>Shengda</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Yang </ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>最近三年任职婴儿车生产线经理。负责计划生产线预算、订购零部件以及监督所有质保环节. 在从事生产管理之前，曾在婴儿车生产线上工作五年(三年是求学期间兼职，毕业后两年全职)，在此期间，不断得到提升。刚开始是从事基本组装，后升为刹车系统质保主管. 带领团队通过 ISO 9000 认证. 通过州举办的化学和工业安全考试。最近又通过再认证获得基本急救证书. 爱好自行车，在奥兰多地区举办的两次自行车比赛中排名前五.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>1994-09-15Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-01-08Z</ns:Emp.EndDate><ns:Emp.OrgName>Wingtip Toys</ns:Emp.OrgName><ns:Emp.JobTitle>生产经理</ns:Emp.JobTi',1498176000
10,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix/><ns:Name.First>Tai</ns:Name.First><ns:Name.Middle/><ns:Name.Last>Yee</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>我是一名经验丰富的机械师，技术全面，不仅单独操作各种机械设备，还管理其他机械师的工作。我专攻诊断和精度检测，可以读懂设计图，能够妥善处理各方面的人际关系并具备良好的沟通能力来指导我管辖的机械师的工作. 与其他候选者相比，我拥有的机械工程学位使我对机械师行业在理论方面具有更深刻的了解，数学背景知识也更深厚.
    </ns:Skills><ns:Employment><ns:Emp.StartDate>2000-06-15Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-09-18Z</ns:Emp.EndDate><ns:Emp.OrgName>Wingtip Toys</ns:Emp.OrgName><ns:Emp.JobTitle>机械师主管</ns:Emp.JobTitle><ns:Emp.Responsibility>管理四名机械师的工作. 协调所有复杂的组装和工具使用，包括三轮',1498176000
11,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix>นาย</ns:Name.Prefix><ns:Name.First>สุทัศน</ns:Name.First><ns:Name.Middle/><ns:Name.Last>คณาพล</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>มีความชำนาญในสายงานขายอย่างมาก  ประสบความสำเร็จตลอด 13 ปีในการเพิ่มรายได้ให้กับองค์กร มีประสบการณ์ในการวางแผนงานขาย และการประมาณการ การพัฒนาธุรกิจ และเทคนิคการขายหลากหลายประเภท 
ประสบการณ์ 5 ปีในการบริหารงานขาย รวมถึงการสร้างโอกาสทางการขาย การนำทีมขาย และก',1498176000
12,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix>นาย </ns:Name.Prefix><ns:Name.First>สามารถ</ns:Name.First><ns:Name.Middle/><ns:Name.Last>เบญจศร</ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills>ประสบการณ์ล่าสุดกว่า 3 ปีในตำแหน่งผู้จัดการสายการผลิตรถโกคาร์ท  ความรับผิดชอบ ประกอบด้วยการวางแผนงบประมาณของสายการผลิต การสั่งซื้ออะไหล่ และควบคุมกระบวนการประกันคุณภาพ 
ก่อนรับตำแหน่งบริหารการผลิต ได้ทำงานในสายการผลิตรถโกคาร์ทกว่า 5 ปี (3 ปีขณะศึกษา และ 2 ป',1498176000
13,.,'<ns:Resume xmlns:ns="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/Resume"><ns:Name><ns:Name.Prefix/><ns:Name.First>ชาย </ns:Name.First><ns:Name.Middle/><ns:Name.Last>บางสุขศรี </ns:Name.Last><ns:Name.Suffix/></ns:Name><ns:Skills/><ns:Employment><ns:Emp.StartDate>2000-06-15Z</ns:Emp.StartDate><ns:Emp.EndDate>2002-09-11Z</ns:Emp.EndDate><ns:Emp.OrgName>บริษัท เมจิค ทอยส์ </ns:Emp.OrgName><ns:Emp.JobTitle>หัวหน้าช่างยนต์</ns:Emp.JobTitle><ns:Emp.Responsibility>ดูแลงานของกลุ่มช่างสี่คน 
ประสานงานประกอบที่มีความซับซ้อน และการใช้เครื่องมือหนัก รวมถึงการผลิตจักรยานสามล้อและรถเข็น 
พัฒนาการผลิตอะไหล่จากชิ้นส่วนตัวอย่าง',1498176000
;;;;
run;
proc append base=hr.JobCandidate data=work.JobCandidate;run;
