/* DDL generated by allbow on  27SEP2021:17:50:12 */
/* SAS Flavour DDL for HR. */
proc sql;
create table hr.SHIFT(
    ShiftID num format=4. not null label='ShiftID'
   ,Name char(100) format=$100. not null label='Name'
   ,StartTime num format=TIME8. not null label='StartTime'
   ,EndTime num format=TIME8. not null label='EndTime'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
