/* DDL generated by allbow on  27SEP2021:17:51:58 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.COUNTRYREGIONCURRENCY(
    CountryRegionCode char(6) format=$6. not null label='CountryRegionCode'
   ,CurrencyCode char(6) format=$6. not null label='CurrencyCode'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
