/* DDL generated by allbow on  27SEP2021:17:51:59 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.CREDITCARD(
    CreditCardID num format=11. not null label='CreditCardID'
   ,CardType char(100) format=$100. not null label='CardType'
   ,CardNumber char(50) format=$50. not null label='CardNumber'
   ,ExpMonth num format=4. not null label='ExpMonth'
   ,ExpYear num format=6. not null label='ExpYear'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
