/* DDL generated by allbow on  27SEP2021:17:52:02 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.CURRENCY(
    CurrencyCode char(6) format=$6. not null label='CurrencyCode'
   ,Name char(100) format=$100. not null label='Name'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
