/* DDL generated by allbow on  27SEP2021:17:52:23 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.SALESPERSONQUOTAHISTORY(
    BusinessEntityID num format=11. not null label='BusinessEntityID'
   ,QuotaDate num format=DATETIME22.3 not null label='QuotaDate'
   ,SalesQuota num format=21.4 not null label='SalesQuota'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
