/* DDL generated by allbow on  27SEP2021:17:52:19 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.SALESORDERHEADERSALESREASON(
    SalesOrderID num format=11. not null label='SalesOrderID'
   ,SalesReasonID num format=11. not null label='SalesReasonID'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
