/**
  @file
  @brief Datalines for SALESREASON dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.SalesReason ;
attrib 
SalesReasonID                    length= 8      format=11. label="SalesReasonID"
Name                             length= $100   format=$100. label="Name"
ReasonType                       length= $100   format=$100. label="ReasonType"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  SalesReasonID
  Name                             :$char.
  ReasonType                       :$char.
  ModifiedDate
;
datalines4;
1,Price,Other,1525132800
2,On Promotion,Promotion,1525132800
3,Magazine Advertisement,Marketing,1525132800
4,Television  Advertisement,Marketing,1525132800
5,Manufacturer,Other,1525132800
6,Review,Other,1525132800
7,Demo Event,Marketing,1525132800
8,Sponsorship,Marketing,1525132800
9,Quality,Other,1525132800
10,Other,Other,1525132800
;;;;
run;
proc append base=sales.SalesReason data=work.SalesReason;run;
