/**
  @file
  @brief Datalines for SALESTAXRATE dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.SalesTaxRate ;
attrib 
SalesTaxRateID                   length= 8      format=11. label="SalesTaxRateID"
StateProvinceID                  length= 8      format=11. label="StateProvinceID"
TaxType                          length= 8      format=4. label="TaxType"
TaxRate                          length= 8      format=12.4 label="TaxRate"
Name                             length= $100   format=$100. label="Name"
rowguid                          length= $36    format=$36. label="rowguid"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  SalesTaxRateID
  StateProvinceID
  TaxType
  TaxRate
  Name                             :$char.
  rowguid                          :$char.
  ModifiedDate
;
datalines4;
1,1,1,14,Canadian GST + Alberta Provincial Tax,683DE5DD-521A-47D4-A573-06A3CDB1BC5D,1525132800
2,57,1,14.25,Canadian GST + Ontario Provincial Tax,05C4FFDB-4F84-4CDF-ABE5-FDF3216EA74E,1525132800
3,63,1,14.25,Canadian GST + Quebec Provincial Tax,D4EDB557-56D7-403C-B538-4DF5E7302588,1525132800
4,1,2,7,Canadian GST,F0D76907-B433-453F-B95E-16FCE73B807A,1525132800
5,57,2,7,Canadian GST,7E0E97A2-878B-476F-A648-05A3DD4450ED,1525132800
6,63,2,7,Canadian GST,1E285D2C-8AF7-47AA-B06A-762CF4D93ACD,1525132800
7,7,3,7,Canadian GST,590CCB14-CB20-49BF-8FEE-E0C3ABC4C2B1,1525132800
8,29,3,7,Canadian GST,A8365F30-78B7-4DBE-8985-F8260560126B,1525132800
9,31,3,7,Canadian GST,F4FDE24B-7A53-4340-9D10-173E9424864A,1525132800
10,41,3,7,Canadian GST,383D465B-E1D1-492A-83F3-AB3E9CBF3282,1525132800
11,45,3,7,Canadian GST,8451909F-8A8D-4789-9F87-16A335D28053,1525132800
12,49,3,7,Canadian GST,FB7607EE-8F12-41EA-B461-10885C6F1533,1525132800
13,51,3,7,Canadian GST,06DF529D-EB11-446F-9570-9EE97B8EA1BF,1525132800
16,69,3,7,Canadian GST,89D447A8-239A-4F31-A529-478821E8F714,1525132800
17,83,3,7,Canadian GST,3847B431-F939-4E89-83FC-864912E3CFD2,1525132800
18,6,1,7.75,Arizona State Sales Tax,89DD0E3A-C018-449E-A86B-885ADF684C5C,1525132800
19,9,1,8.75,California State Sales Tax,90E3090E-DF71-407A-8059-04C3104523AF,1525132800
20,15,1,8,Florida State Sales Tax,630AE36F-6E76-4A1F-AB25-6342159C80D2,1525132800
21,30,1,7,Massachusetts State Sales Tax,207C7024-85FE-42CB-BF74-9FE88E2F4E1B,1525132800
22,35,1,7.25,Michigan State Sales Tax,F9D1A85D-6474-43B5-A7EA-BED59E00439A,1525132800
23,36,1,6.75,Minnesota State Sales Tax,1753D75F-8357-4497-BC92-543F17BBF514,1525132800
24,72,1,7.25,Tennessese State Sales Tax,ECBA1BAB-A7A6-4CC2-8D0F-C094A38E5C0E,1525132800
25,73,1,7.5,Texas State Sales Tax,D50102E1-0150-43F3-93AD-12AB6C1DEB06,1525132800
26,74,1,5,Utah State Sales Tax,5E6D8621-36AF-40CE-972B-61AAEF0556D8,1525132800
27,79,1,8.8,Washington State Sales Tax,9C84C0AF-41CD-4670-98BC-5026E188541F,1525132800
28,77,3,10,Taxable Supply,F53B6A7E-7DA4-49E8-AC09-D57FEFAC64D3,1525132800
29,20,3,16,Germany Output Tax,78C8A559-4D0F-45B6-B7A3-E11FF9A702F4,1525132800
30,84,3,19.6,France Output Tax,5446EA04-FA7C-4B02-A157-A05F44BF47B6,1525132800
31,14,3,17.5,United Kingdom Output Tax,ABD185A9-5367-44E1-8A6E-71D083943F3C,1525132800
;;;;
run;
proc append base=sales.SalesTaxRate data=work.SalesTaxRate;run;
