/**
  @file
  @brief Datalines for SHOPPINGCARTITEM dataset
  @details Generated by %mp_ds2cards()
  Available on github.com/sasjs/core
**/
data work.ShoppingCartItem ;
attrib 
ShoppingCartItemID               length= 8      format=11. label="ShoppingCartItemID"
ShoppingCartID                   length= $100   format=$100. label="ShoppingCartID"
Quantity                         length= 8      format=11. label="Quantity"
ProductID                        length= 8      format=11. label="ProductID"
DateCreated                      length= 8      format=DATETIME22.3 label="DateCreated"
ModifiedDate                     length= 8      format=DATETIME22.3 label="ModifiedDate"
;
infile cards dsd delimiter=',';
input 
  ShoppingCartItemID
  ShoppingCartID                   :$char.
  Quantity
  ProductID
  DateCreated
  ModifiedDate
;
datalines4;
2,14951,3,862,1699638847.603,1699638847.603
4,20621,4,881,1699638847.603,1699638847.603
5,20621,7,874,1699638847.603,1699638847.603
;;;;
run;
proc append base=sales.ShoppingCartItem data=work.ShoppingCartItem;run;
