/* DDL generated by allbow on  27SEP2021:17:52:34 */
/* SAS Flavour DDL for SALES. */
proc sql;
create table sales.SPECIALOFFERPRODUCT(
    SpecialOfferID num format=11. not null label='SpecialOfferID'
   ,ProductID num format=11. not null label='ProductID'
   ,rowguid char(36) format=$36. not null label='rowguid'
   ,ModifiedDate num format=DATETIME22.3 not null label='ModifiedDate'
);
